In [ ]:
# kzo-sjzy-ddq
import numpy as np
a = np.array([[1,2,3],[7,6,9],[7,4,9]])
res = np.transpose(a)
print(res)#convert rows into columns ,

[[1 7 7]
 [2 6 4]
 [3 9 9]]


In [8]:
#concatenate joining arrays 
import numpy as np
a = np.array([[1,2,3],[6,8,9]])
b = np.array([[7,4,9],[2,5,6]])



# res = np.concatenate((a,b))
res = np.concatenate((a,b),axis =1)
print(res)# double bracket dena taki baki parameters bhi use kar sakte hain ex axis 


[[1 2 3 7 4 9]
 [6 8 9 2 5 6]]


In [ ]:
#splitting arrays 
a = np.arange(9)
print(a)#0 se 9 
res  = np.split(a,3)
print(res)# 3,3 ke array main divide kar dega 
for i , arr in  enumerate(res):
    print("spliited array",i+1)# splitted array sundar likhne ka tarika
    print(arr)#

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
spliited array 1
[0 1 2]
spliited array 2
[3 4 5]
spliited array 3
[6 7 8]


In [ ]:
a = np.array([[1,2,3],[4,5,66]])
print(a.shape)# 2*3 ka rray banega
res = np.resize(a,(3,2))# 3 *2 ka matrix banega 
print(res)

(2, 3)
[[ 1  2]
 [ 3  4]
 [ 5 66]]


In [24]:
#append to last of the file 
a = np.array([[1,2,3],[4,5,6]])
res = np.append(a,[[7,8,9],[4,5,6]],axis =1)
print(res)

[[1 2 3 7 8 9]
 [4 5 6 4 5 6]]


In [ ]:
res = np.insert(a,3,[11,12])
print(res)# to inser element at 3rd indedx 

[ 1  2  3 11 12  4  5  6]


In [28]:
a= np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,6))#delete 6 element 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  7  8  9 10 11]


In [30]:
#flip()
#sorting
a = np.array([24,32,34,65,3,2,43])
res = np.sort(a)
print(res)

[ 2  3 24 32 34 43 65]


In [33]:
a = np.array([24,32,34,65,3,2,43])
res = np.argmax(a)
print(res)

3


In [ ]:
#indexing and slicing 
a =np.arange(10)
res = a[4::]# 4 se lekar akhir tak  print hoga
print(res)


[4 5 6 7 8 9]


In [39]:
a= np.array([[1,2,30],[4,5,6]])
a.shape=(3,2)
print(a.shape)

(3, 2)


In [45]:
a = np.arange(24)
a.ndim
res = a.reshape(2,3,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [47]:
a =np.array([
    [[1,2,3,],[2,3,4]],
    [[2,3,4],[5,67,8]]
]
)
print(a)

[[[ 1  2  3]
  [ 2  3  4]]

 [[ 2  3  4]
  [ 5 67  8]]]


In [ ]:
a =np.array([
    [[1,2,3,],[2,3,4]],
    [[2,3,4],[5,67,8]]
],dtype = np.float32
)
print(a,a.dtype)

[[[ 1  2  3]
  [ 2  3  4]]

 [[ 2  3  4]
  [ 5 67  8]]] int32


In [49]:
a =np.array([
    [[1,2,3,],[2,3,4]],
    [[2,3,4],[5,67,8]]
],dtype = np.float32
)
print(a,a.dtype)

[[[ 1.  2.  3.]
  [ 2.  3.  4.]]

 [[ 2.  3.  4.]
  [ 5. 67.  8.]]] float32


In [50]:
#arithmetic opressions 
a = np.array([11,12,13])
b = np.array([22,34,76])
print(a%b)

[11 12 13]


In [53]:
a= np.array([[1,2,30],[4,5,6]])
b= np.array([[3,45,30],[41,45,6]])
print(a+b)
print(a-b)
print(a*b)
print(a%b)



[[ 4 47 60]
 [45 50 12]]
[[ -2 -43   0]
 [-37 -40   0]]
[[  3  90 900]
 [164 225  36]]
[[1 2 0]
 [4 5 0]]


In [ ]:
#power operation a =np.array([1,2,40])
#sum operation calculates 
import numpy as np 
a= np.array([[11,21,32],[32,43,54]])

# res = np.sum(a,axis=0)# axis 0 means rows 
res = np.sum(a)# axis 0 means rows  uske bina sare ekmeents ka sum aajayega 
print(res)

193


In [58]:
#mean operation
import numpy as np 
a= np.array([[11,21,32],[32,43,54]])


res = np.mean(a,axis=0)# axis 0 means rows 
#res = np.mean(a)# axis 0 means rows  uske bina sare ekmeents ka sum aajayega 
print(res)

[21.5 32.  43. ]


In [60]:
import numpy as np 
a= np.array([[11,21,32],[32,43,54]])

res = np.mean(a,axis=1)# axis 0 means rows 

print(res)

[21.33333333 43.        ]


In [62]:
#complex numbers - imag -imagianry part return karega 
import numpy as np 
a= np.array([11.34j,2.8j,1+3j])
print(np.conj(a))
print(np.angle(a,deg = True))
# res = np.sum(a,axis=0)# axis 0 means rows 
res = np.sum(a)# axis 0 means rows  uske bina sare ekmeents ka sum aajayega 
print(res)


[0.-11.34j 0. -2.8j  1. -3.j  ]
[90.         90.         71.56505118]
(1+17.14j)
