In [3]:
import numpy as np


In [4]:
print(np.__version__)

2.3.5


In [5]:
a = np.array([1,2,3])
print(a,type(a))
print(a,type(a), a.dtype)

[1 2 3] <class 'numpy.ndarray'>
[1 2 3] <class 'numpy.ndarray'> int64


In [6]:

print(a)# no of square braa = np.array([[1,2],[3,4]])ckets tell us dimension of vector  like here it is 2 dimension array

[1 2 3]


In [7]:
a = np.array([
    [1,2,5,6]
    ,[3,4,7,8]
    ])
print(a)# no of square brackets tell us dimension of vector  like here it is 2 dimension array

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
#data type int 6,8,32,64 bitt ,float 128 floating point numberr 
#complex number 128 2 64 bit float s 

In [9]:
#boolean ,string ,unicode , timedelta,fixed chunk for other type void 
a = np.array([
    ['a','b','c','d']
    ,[3,4,7,8]
    ])
print(a,type(a))

[['a' 'b' 'c' 'd']
 ['3' '4' '7' '8']] <class 'numpy.ndarray'>


In [10]:
a = np.array([
    1,2,3
],dtype='S')
print(a)

[b'1' b'2' b'3']


numpy.array()function  array banane main madad karega 
zeroes zeroes fill kardega
ones one fill kardega

In [11]:
a = np.zeros(5)
print(a,type(a),a.dtype)

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'> float64


In [12]:
a = np.ones(5)
print(a,type(a),a.dtype)

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'> float64


In [13]:
a = np.zeros((6,2))
print(a,type(a),a.dtype)# agar 2 dimensiion arrow creation 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] <class 'numpy.ndarray'> float64


In [14]:
#fortran #used for mathematical operation a lot 

In [15]:
a = np.ones((6,2),order = "F")
print(a,type(a),a.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] <class 'numpy.ndarray'> float64


In [16]:
a =np.arange(1,10,2)
print(a)# for creating an array 

[1 3 5 7 9]


In [17]:
#linespace 

In [18]:
a = np.linspace(0,5,num=10)
print(a)# float number will be print from 0 to 5 randome numbers 

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [19]:
a = np.linspace(0,5,num=10)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [20]:
#random.rand() function ()ye randum value lega 
a = np.random.rand(5)# single dimension lyonki 
print(a)

[0.98353321 0.11088649 0.97208448 0.7967276  0.04709097]


In [21]:
a = np.random.rand(3,2,4)# for 3 dimension vectore 
print(a)

[[[0.18777962 0.34972803 0.94979085 0.66948773]
  [0.36789336 0.56966603 0.67506916 0.40845781]]

 [[0.59842762 0.93723578 0.84089733 0.57751733]
  [0.87497759 0.67949253 0.79352824 0.14373583]]

 [[0.37230736 0.57587758 0.3427921  0.99040274]
  [0.78130062 0.59360835 0.05735355 0.70986595]]]


In [22]:
#numpy.empty() array create karega lekin kuch bhi fill nhi karega 
a= np.empty(3)
print(a)

[7.74860419e-304 7.74860419e-304 7.74860419e-304]


In [23]:
#np.zeros()  ,numpy.full((2,3),5)
#2,3 ka array or 5 fill karega
a = np.full((3,2),6)
print(a)

[[6 6]
 [6 6]
 [6 6]]


In [24]:
#random.rand ke differnt function try
#acces aray using index
a= np.array([1,2,3,4,5])
print(a[3])
print(a[2]+a[3])


4
7


In [25]:
# 2 dimen array ko access karne ke liye 
a = np.array([[1,2,3,4,5],
             [6,7,8,9,0,]])
print(a[1,3])

9


In [26]:
#3 dim array
a = np.array(
    [
    [[1,2,3,4,5],
               [2,3,4,5,6]],
    [[34,5,556,76,87],
               [45,3,4,54,53]]
               ])
print(a[0,1,3])

5


In [27]:
print(a[1,1,-1])

53


In [28]:
#using slicing in 3 dimension array - taking one elemnt from one index to other 
#dont start =0
a= np.array([1,2,3,4,4])
print(a[1:4:])

[2 3 4]


In [29]:
a= np.array([1,2,3,4,4,23,34,45])
print(a[1:7:2])# slicing(start:end:kitne ka gap rakhna hai )

[ 2  4 23]


In [30]:
a = np.array([[1,2,2,3,4],
              [3,4,5,43,566]])
print(a[0:1,1:3])

[[2 2]]


In [31]:
#3 dimension array explained / 3 d array  first axis = no of 2d array
#second axis = nomber of rows in each 2d array 
#third = no of 3rd column 

#same no of elemnts all of same data 
a = np.array([
    [[1,2,2,3,4],
              [3,4,5,43,566],
    [23,43,54,65,43]],
              [[2,334,54,34,32],
    [23,12,34,54,65],
               [23,32,43,5456,54]
               ]])
print(a)
print(a.shape)


[[[   1    2    2    3    4]
  [   3    4    5   43  566]
  [  23   43   54   65   43]]

 [[   2  334   54   34   32]
  [  23   12   34   54   65]
  [  23   32   43 5456   54]]]
(2, 3, 5)


In [32]:
a = np.zeros((3,4,5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
# a= np.fill((0:3),3)
# copy copy create karega (a bana  a= aaray b kaiya a ka value b main 
#ndmin min number odf diension of array #
# copy of new array view origional array ka copy hoga 
#copy wale main duplicate change kiya to kuch change nhi hoga 
# view main jo bhi change hoga wo real main bhi vhange ho jayega  
a=np.array([1,2,3,4,5])
x= a.copy()
a[0]=50
print(a)# copy main chang nhi hoga agar origional main change kiya hai 
print(x)


[50  2  3  4  5]
[1 2 3 4 5]


In [34]:
a=np.array([1,2,3,4,5])
x= a.view()#x main a ka instance origional copy , copy main bhi change ho jayega 
a[0]=50
print(a)
print(x)

[50  2  3  4  5]
[50  2  3  4  5]


In [35]:
x = a.view()
y = a.copy()
print(x.base)
print(y.base)
#reshape shape change karega 

[50  2  3  4  5]
None


In [36]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,4))# 1d ko 2d main convert kar diya 

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
    #htk-ppeh-nbb
a = np.array([[1,2,3,4,5],
             [6,7,8,9,0,]])
print(a.shape)


(2, 5)


In [38]:
a = np.array([1,2,3,4,5,6,7],ndmin =7)
print(a)
print(a.shape)

[[[[[[[1 2 3 4 5 6 7]]]]]]]
(1, 1, 1, 1, 1, 1, 7)


In [39]:
#reshape from 1 to 3d reshape (2,3,2)
a = np.array([[1,2,3,4,5],
             [6,7,8,9,0,]])

print(a.shape)


(2, 5)


In [40]:
print(np.unique(a))
print(a.sum())
print(np.std(a))
print(np.sqrt(a))





[0 1 2 3 4 5 6 7 8 9]
45
2.8722813232690143
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         0.        ]]


In [41]:
a = np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
x=a.dot(b)
print(x)

[[37 40]
 [85 92]]


In [ ]:
#padding operation dono side array ke 0 add kar dega ,reshape karna ho to padding ka istemaal kar sakte hain
a= np.array([1,3,4,5,5])
a[1],a[4] = a[4],a[1]      # swap nubers betwwn 2 and 3 
print(a)

[1 5 4 5 3]


In [ ]:
#2 dimensinal array
a = np.array([[1,2,34,4,5],[6,7,8,9,7],[5,6,7,8,8]])
print(a[1][1])
a[1][1]=a[2][2]
a[[0,2],:] = a[[2,0],:]# swaping rows  0 or 2 row ko swap kar rahe hain , teeno ko karna hoga to hame 
print(a)# colon ke bad main main columns ka value hota hai agar colon ko swap karana hoga to 

[[ 1  2 34  4  5]
 [ 6  7  8  9  7]
 [ 5  6  7  8  8]]
[[ 5  6  7  8  8]
 [ 6  7  8  9  7]
 [ 1  2 34  4  5]]


In [45]:
a = np.array([[1,2,34,4,5],[6,7,8,9,7],[5,6,7,8,8]])
print(a[1][1])
a[1][1]=a[2][2]
a[:,[0,2]] = a[:,[2,0]]# swaping rows  0 or 2 row ko swap kar rahe hain , teeno ko karna hoga to hame 
print(a)

7
[[34  2  1  4  5]
 [ 8  7  6  9  7]
 [ 7  6  5  8  8]]


In [ ]:
a = np.array(
    [[ [1,2,3],[4,5,6]],
    [ [7,8,9],[0,1,2] ] ])
print(a)
a[[0,1],[0,1],:]=a[[1,0],:,:]
print(a)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
[[[7 8 9]
  [0 1 2]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a= np.array(
  [1,2,np.nan,4,np.nan,6]
 )# jahan pe nan hai wahan par true aa jayega 
res = np.isnan(a)
print(a)
print(res)

[ 1.  2. nan  4. nan  6.]
[False False  True False  True False]


In [53]:
res = a[~np.isnan(a)]
print(a)
print(res)

[ 1.  2. nan  4. nan  6.]
[1. 2. 4. 6.]


In [ ]:
#np.nan to num 
res = np.nan_to_num(a,nan=0)
print(a)
print(res)# 0 dal dega nan ke jagah

[ 1.  2. nan  4. nan  6.]
[1. 2. 0. 4. 0. 6.]


In [ ]:
#.npy file 
a= np.array(
  [[1,2,3,4,5],[11,22,33,44,55]]
 )
np.save('data.npy',a)#read npy file 

In [58]:
res = np.load('data.npy')
print(res)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [59]:
#.npz file  complex file hai jo 
b= np.array([23,45,7])
np.savez('data.npz',arr1=a,arr2=b)


In [61]:
#read karna hai to 
res = np.load('data.npz')
print(res['arr1'])

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


In [67]:
#reading and writing text file 
#load.txt data koad kaayega 
with open('data.txt','w')as f:
  f.write("1.0 2.0 3.0\n4.0 5.0 6.0\n8.0 9.0 10.0")
data = np.loadtxt('data.txt')
print(data)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 8.  9. 10.]]


In [69]:
#handling csv files numpy.genfromtxt() function loads daata from a file 
with open('data.csv','w')as f:
  f.write("1.0 2.0 3.0\n4.0 5.0 6.0\n8.0 9.0 10.0")
data = np.genfromtxt('data.csv', delimiter =',')
print(data)

[nan nan nan]


In [73]:
# 3x+2y=5
# x+2y =5 
a = np.array([[3,2],[1,2]])
a2 = np.array([5,5])
res = np.linalg.solve(a, a2)
print("answer",res)

answer [2.96059473e-16 2.50000000e+00]


In [ ]:
a = np.array([[4,2],[1,2]])
a2 = np.array([5,5])
res = np.linalg.solve(a, a2)
print("answer",res)

In [75]:
#alternative waya = 
np.array([[4,2],[1,2]])
a2 = np.array([5,5])
res = np.linalg.inv(a)
print("answer",res)#s to slove liinear equation
#np.linalg

answer [[ 0.5  -0.5 ]
 [-0.25  0.75]]


In [ ]:
#graph 